# Site Settings
title: "Your Name"
name: "Your Name"
description: "Your personal site"
url: "https://firefast1111.github.io"
baseurl: ""
repository: "firefast1111/firefast1111.github.io"

# Jekyll & Theme
remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache

# Add this to force newer Liquid version
liquid:
  error_mode: strict

# Minimal Mistakes Settings
minimal_mistakes_skin: "default"

# Site Author
author:
  name: "Your Name"
  bio: "Your short bio"
  location: "Your Location"
  email: "your.email@example.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/firefast1111"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/yourusername"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/yourusername"

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      share: true
      comments: false
