title: My Jekyll Site
description: A simple Jekyll site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site
remote_theme: "minima"
