# Site Settings
title: "Your Name"
name: "Your Name"
description: "Your personal site"
url: "https://firefast1111.github.io"
baseurl: ""
repository: "firefast1111/firefast1111.github.io"

# Theme Settings
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "dark" # Options: dark, dirt, neon, plum

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Site Author
author:
  name: "Your Name"
  bio: "Your short bio"
  location: "Your Location"
  email: "your.email@example.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/firefast1111"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/yourusername"

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      share: true
      comments: false
