name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: false # Disable bundler cache to prevent conflicts
      
      - name: Install exact versions
        run: |
          # First install specific versions of problematic gems
          gem install webrick -v 1.8.1
          gem install jekyll -v 4.3.3
          gem install jekyll-remote-theme -v 0.4.3
          gem install jekyll-include-cache -v 0.2.1
          gem install github-pages -v 228 --conservative
          gem install sass-embedded -v 1.77.1
      
      - name: Build with Jekyll
        run: |
          jekyll build --trace --destination ./_site
      
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
